### ISSUE TITLE
[MNT] maintenance & handover roadmap

### ISSUE THREAD

**Issue by fkiraly** [jdb78/pytorch-forecasting#1592]
We are currently planning a maintenance handover of `pytorch-forecasting` to `sktime`. Both packages will remain separate, with `pytorch-forecasting` on the "models" level, and `sktime` providing framework integration.

This issue is to plan urgent maintenance items and handover (to `sktime` maintenance model).

### Maintenance items

- [ ] soft dependency review and potential isolation (e.g., `optuna` or `matplotlib`, not needed for NN models core)
- [ ] pyproject review, dependabot PRs
- [ ] stale PR review and triage
- [ ] failing CI fixes
- [ ] failing docs
- [ ] python 3.11, 3.12; EOL for 3.8

### handover items

- [ ] issue triage
- [ ] operational handover
- [ ] digital assets
- [ ] release pipeline

### roadmap wishlist

- [ ] refactor model level tests to systematic test suite?

**Comment by fkiraly** [comment]
FYI sktime developers who have worked on the integration, @benheid, @fnhirwa, @geetu040, @xinyuwuu, @yarnabrina

**Comment by fkiraly** [comment]
At the very start, we need to get the CI run again.
Reason for failures:

* linting failures
* `numpy 2` incompatibility at missing version bound, #1594
* `optuna >= 3.3.0` incompatibility at missing version bound, #1595
* MPS backend memory failures https://github.com/jdb78/pytorch-forecasting/issues/1596

Suggested measures:

* allow force-push for maintainers, that allows PR that fix part of but not all failures
* move the pyproject to `pip` from `poetry`, this makes work on CI easier
* lint with `black`, and change linter to only look at changed files
* add bounds to incompatible versions, fix later
* then fix the remaining failure, MPS backend issue

**Comment by XinyuWuu** [comment]
Fixing tutorial notebooks is also very important: https://github.com/jdb78/pytorch-forecasting/pull/1599

**Comment by fkiraly** [comment]
of course - we won't know whether we fixed them though if the CI does not run

**Comment by XinyuWuu** [comment]
Regarding the dependency management, maybe we should not minimize core dep set.

Comparing to `torch`, `lightning`, `optuna`, other packages are too small to make a difference to installation time.

It could be a disaster if a lot a time has been spent to train the model, and then some soft dependency error comes out.

So maybe we should make sure that users have almost all the functionalities with the core dep set.

**Comment by fkiraly** [comment]
Agree, though even small dependencies pose a risk of reducing the degree of interoperability on the level of dependencies. Suppose you have `small_package` which has a very restrictive dependency set, or `small_package2` which is the only dependency that never upgrades to `numpy 2` or `python 3.12`.

Further, I wonder about how central `optuna` is here. It is important for tuning, but its purpose seems extraneous to the primary defining topic of deep learning based forecasters.

**Comment by XinyuWuu** [comment]
> Further, I wonder about how central `optuna` is here. It is important for tuning, but its purpose seems extraneous to the primary defining topic of deep learning based forecasters.

It's only used in [pytorch_forecasting/models/temporal_fusion_transformer/tuning.py](https://github.com/jdb78/pytorch-forecasting/blob/master/pytorch_forecasting/models/temporal_fusion_transformer/tuning.py) to tune TemporalFusionTransformer. So I guess it's not so central.

**Comment by XinyuWuu** [comment]
> Agree, though even small dependencies pose a risk of reducing the degree of interoperability on the level of dependencies. Suppose you have `small_package` which has a very restrictive dependency set, or `small_package2` which is the only dependency that never upgrades to `numpy 2` or `python 3.12`.

Yeah, that could be a problem. We could have two dep sets `core` and `compatible` and put those packages that don't fit in well in `compatible` set.

**Comment by fkiraly** [comment]
I think this has progressed enough to be considered complete. The remaining open issues can be dealt with in separate issues.
